# FLYWAY (FlywayProperties)
#flyway:
#  baseline-description:  #
#  baseline-version: 1 # version to start migration
#  baseline-on-migrate:  #
#  check-location: false # Check that migration scripts location exists.
#  clean-on-validation-error:  #
#  enabled: true # Enable
#  encoding:  #
#  ignore-failed-future-migration:  #
#  init-sqls:  # SQL statements to execute to initialize a connection immediately after obtaining it.
#  locations: classpath:db/migration # locations of migrations scripts
#  out-of-order:  #
#  password:  # JDBC password if you want Flyway to create its own DataSource
#  placeholder-prefix:  #
#  placeholder-replacement:  #
#  placeholder-suffix:  #
#  placeholders.*:  #
#  schemas :  # schemas to update
#  sql-migration-prefix: V #
#  sql-migration-separator:  #
#  sql-migration-suffix: .sql #
#  table:  #
#  url:  # JDBC url of the database to migrate. If not set, the primary configured data source is used.
#  user:  # Login user of the database to migrate.
#  validate-on-migrate:  #

spring:
  datasource:
    dbname: script_manager
    url_properties: "?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/${spring.datasource.dbname}${spring.datasource.url_properties}"
    username: inthub
    password: inthub
